const platforms = [
  "PC",
  "PlayStation 5",
  "PlayStation 4",
  "Xbox One",
  "Xbox Series S/X",
  "Nintendo Switch",
  "iOS",
  "Android",
  "Nintendo 3DS",
  "Nintendo DS",
  "Nintendo DSi",
  "Nintendo DSi",
  "macOS",
  "Linux",
  "Xbox 360",
  "Xbox",
  "PlayStation 3",
  "PlayStation 2",
  "PlayStation",
  "PS Vita",
  "PSP",
  "Wii U",
  "Wii",
  "GameCube",
  "Nintendo 63",
  "Game Boy Advance",
  "Game Boy Color",
  "Game Boy",
  "SNES",
  "NES",
  "Classic Macintosh",
  "Apple II",
  "Commodore / Amiga",
  "Atari 7800",
  "Genesis",
  "SEGA CD",
];

module.exports = platforms;
